name: Run

on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '0 23 * * *'   # 每天北京时间 7:00（UTC 23:00）

jobs:
  build:

    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Run
      uses: coactions/setup-xvfb@main
      with:
        run: dotnet Program.cs
      env: 
        CONF: ${{ secrets.CONF }}
